vich_uploader:
    db_driver: orm

    mappings:
        ingredient_image:
            uri_prefix: /images/ingredients
            upload_destination: '%kernel.project_dir%/public/images/ingredients'

    # Doc
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
